packages:
  - 'frontend'
  - 'backend/skill-node'
ignoredOptionalDependencies:
  - '@img/sharp-*'
  - '@img/sharp-libvips-*'
  - sharp
allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  msw: true
  sharp: true
  unrs-resolver: true
